name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '42 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git clone https://git.tt-rss.org/fox/tt-rss.git/ ttrss --depth 1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          tags: ghcr.io/burned42/ttrss-docker:latest
          push: true
