name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '42 5 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git clone https://git.tt-rss.org/fox/tt-rss.git/ src
      - run: ls -la *
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          pull: true
          tags: ghcr.io/burned42/ttrss-docker:latest
          push: true
